language: node_js
sudo: false

node_js:
  - lts/*

cache:
  yarn: true
  directories:
    - 'node_modules'

env:
  CI=true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install

before_script:
  - node --version
  - yarn --version

jobs:
  include:
    - stage: test
      before_script:
        - jest --version
        - tsc --version
      script:
        - yarn test:types
        - yarn test:unit -- --ci
    - stage: lint
      before_script:
        - tslint --version
      script:
        - yarn lint
